# Generated by Django 5.1.6 on 2025-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstmodel',
            name='joined_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='firstmodel',
            name='phone',
            field=models.IntegerField(max_length=14, null=True),
        ),
    ]
